/**
 * Frontend mirror of the backend audit event catalogue
 * (`atlas-backend/src/audit-log/catalog/audit-event-catalog.ts`): which
 * filter category every audited action belongs to, and which categories an
 * Academy owner can see at all.
 *
 * The backend already returns `category` on every entry; this mirror exists
 * for the FILTERS (the category select is built from it) and for the
 * coverage test that proves every action has an English and an Arabic
 * sentence. When an action is added to the backend catalogue, add it here
 * and give it copy in `auditLog.json` (both languages) — the test fails
 * until all three agree.
 */
import type { AuditCategory } from '@types';

export const AUDIT_CATEGORIES: readonly AuditCategory[] = [
  'courses',
  'assessments',
  'website',
  'academy',
  'team',
  'students',
  'certificates',
  'reviews',
  'media',
  'domains',
  'live_sessions',
  'payments',
  'subscription',
  'support',
  'security',
  'platform',
];

/** Categories with no tenant-visible action — never offered to an Academy owner. */
const OPERATOR_ONLY_CATEGORIES: ReadonlySet<AuditCategory> = new Set([
  'security',
  'platform',
]);

/** The category filter an Academy owner is offered. */
export const TENANT_AUDIT_CATEGORIES: readonly AuditCategory[] =
  AUDIT_CATEGORIES.filter(
    (category) => !OPERATOR_ONLY_CATEGORIES.has(category)
  );

export const AUDIT_ACTION_CATEGORIES: Readonly<Record<string, AuditCategory>> =
  {
    'course.created': 'courses',
    'course.updated': 'courses',
    'course.published': 'courses',
    'course.unpublished': 'courses',
    'course.archived': 'courses',
    'course.instructor_assigned': 'courses',
    'course.instructor_removed': 'courses',
    'course.completion_rule.updated': 'courses',
    'course_section.created': 'courses',
    'course_section.updated': 'courses',
    'course_section.deleted': 'courses',
    'course_section.reordered': 'courses',
    'course_lesson.created': 'courses',
    'course_lesson.updated': 'courses',
    'course_lesson.content_updated': 'courses',
    'course_lesson.deleted': 'courses',
    'course.curriculum.item_attached': 'courses',
    'course.curriculum.item_detached': 'courses',
    'course.curriculum.items_reordered': 'courses',
    'quiz.created': 'assessments',
    'quiz.updated': 'assessments',
    'quiz.deleted': 'assessments',
    'quiz.override.updated': 'assessments',
    'quiz.override.removed': 'assessments',
    'quiz_attempt.graded': 'assessments',
    'quiz_attempt.invalidated': 'assessments',
    'assignment.created': 'assessments',
    'assignment.updated': 'assessments',
    'assignment.deleted': 'assessments',
    'assignment_submission.graded': 'assessments',
    'website.configuration.updated': 'website',
    'website.visual_identity.updated': 'website',
    'website.published': 'website',
    'website.unpublished': 'website',
    'website_page.created': 'website',
    'website_page.updated': 'website',
    'website_page.deleted': 'website',
    'website_page.published': 'website',
    'website_page.sections_reordered': 'website',
    'website_faq.created': 'website',
    'website_faq.updated': 'website',
    'website_faq.published': 'website',
    'website_faq.archived': 'website',
    'website_testimonial.created': 'website',
    'website_testimonial.updated': 'website',
    'website_testimonial.published': 'website',
    'website_testimonial.archived': 'website',
    'academy.created': 'academy',
    'academy.updated': 'academy',
    'academy.branding.updated': 'academy',
    'academy.archived': 'academy',
    'academy.content_protection.updated': 'academy',
    'academy.video_tier.updated': 'academy',
    'academy.device_policy.updated': 'academy',
    'academy.registration_policy.updated': 'academy',
    'academy.manager.added': 'team',
    'academy.instructor.added': 'team',
    'academy.student.created': 'students',
    'academy.student.added': 'students',
    'academy.student.joined': 'students',
    'academy.student.name_clash_exempted': 'students',
    'academy.student.blocked': 'students',
    'academy.student.unblocked': 'students',
    'academy.student.approved': 'students',
    'academy.student.rejected': 'students',
    'academy.invite.created': 'students',
    'academy.invite.revoked': 'students',
    'enrollment.granted': 'students',
    'enrollment.revoked': 'students',
    'enrollment.expiry_updated': 'students',
    'learning.device_session_takeover': 'students',
    'certificate.issued': 'certificates',
    'certificate.reissued': 'certificates',
    'certificate.revoked': 'certificates',
    'certificate.regenerated': 'certificates',
    'certificate_template.updated': 'certificates',
    'course_review.created': 'reviews',
    'course_review.updated': 'reviews',
    'course_review.deleted': 'reviews',
    'course_review.approved': 'reviews',
    'course_review.rejected': 'reviews',
    'course_review.removed': 'reviews',
    'media.uploaded': 'media',
    'media.archived': 'media',
    'media.asset.purged': 'media',
    'media.video.deleted': 'media',
    'domain.custom_domain_added': 'domains',
    'domain.custom_domain_removed': 'domains',
    'domain.verification_checked': 'domains',
    'domain.platform_check': 'domains',
    'domain.platform_release': 'domains',
    'live_session.created': 'live_sessions',
    'live_session.updated': 'live_sessions',
    'live_session.cancelled': 'live_sessions',
    'live_session.published': 'live_sessions',
    'live_provider.connected': 'live_sessions',
    'live_provider.disconnected': 'live_sessions',
    'live_provider.deauthorized': 'live_sessions',
    'organization.payment_settings.updated': 'payments',
    'organization.payment_gateway.credentials_saved': 'payments',
    'organization.payment_gateway.connection_tested': 'payments',
    'organization.payment_gateway.enabled': 'payments',
    'organization.payment_gateway.disabled': 'payments',
    'payment.proof_submitted': 'payments',
    'payment.approved': 'payments',
    'payment.rejected': 'payments',
    'course_order_payment.approved': 'payments',
    'course_order_payment.rejected': 'payments',
    'academy.payment_method.saved': 'payments',
    'academy.course_payment.proof_submitted': 'payments',
    'academy.course_payment.approved': 'payments',
    'academy.course_payment.rejected': 'payments',
    'course_order.refund_recorded': 'payments',
    'organization.created': 'subscription',
    'organization.onboarding.completed': 'subscription',
    'provisioning_request.created': 'subscription',
    'subscription.trial.redeemed': 'subscription',
    'subscription.gift.granted': 'subscription',
    'subscription.trial.cancelled': 'subscription',
    'subscription.cancelled': 'subscription',
    'subscription.grace_started': 'subscription',
    'subscription.expired': 'subscription',
    'subscription.cancelled_at_period_end': 'subscription',
    'add_on.install': 'subscription',
    'add_on.enable': 'subscription',
    'add_on.disable': 'subscription',
    'add_on.uninstall': 'subscription',
    'support_case.created': 'support',
    'support_case.replied': 'support',
    'support_case.status_changed': 'support',
    'support_case.auto_created': 'support',
    'auth.otp.issued': 'security',
    'auth.otp.failed': 'security',
    'auth.otp.locked_out': 'security',
    'auth.otp.verified': 'security',
    'auth.device.trusted': 'security',
    'auth.device.revoked': 'security',
    'auth.identity.linked': 'security',
    'auth.identity.unlinked': 'security',
    'auth.sessions.revoked': 'security',
    'password_reset.confirmed': 'security',
    'account.deletion.requested': 'security',
    'account.deletion.code_failed': 'security',
    'account.deletion.locked_out': 'security',
    'account.deletion.confirmed': 'security',
    'account.deleted': 'security',
    'account.deleted_by_platform_owner': 'security',
    'plan.created': 'platform',
    'plan.updated': 'platform',
    'plan.pricing_changed': 'platform',
    'plan.trial_config_changed': 'platform',
    'plan.archived': 'platform',
    'platform_settings.updated': 'platform',
    'payment_method.created': 'platform',
    'payment_method.updated': 'platform',
    'commission_config.global_default_updated': 'platform',
    'add_on.catalog_status_changed': 'platform',
    'observability.synthetic_alert.armed': 'platform',
    'observability.synthetic_alert.resolved': 'platform',
    'platform.contact_submission.status_changed': 'platform',
    'platform.contact_submission.deleted': 'platform',
    'platform.campaign.sent': 'platform',
    'academy.message.sent': 'academy',
  };

export const AUDIT_ACTIONS: readonly string[] = Object.keys(
  AUDIT_ACTION_CATEGORIES
);

/** The category of an action, `'other'` for one this build does not know. */
export function auditCategoryOf(action: string): AuditCategory | 'other' {
  return AUDIT_ACTION_CATEGORIES[action] ?? 'other';
}
